# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

gic400_group = Split('''
gic_pl400.c
''')

gic500_group = Split('''
gic_pl500.c
''')

src = src = gic400_group
group = DefineGroup('gic', src, depend = ['RT_USING_GIC'], CPPPATH = CPPPATH)

Return('group')
