/* Generated by mkromfs. Edit with caution. */
#include <rtthread.h>
#include <dfs_romfs.h>

static const rt_uint8_t _romfs_root_dev__gitkeep[] = {
0x20
};

static const struct romfs_dirent _romfs_root_dev[] = {
    {ROMFS_DIRENT_FILE, ".gitkeep", (rt_uint8_t *)_romfs_root_dev__gitkeep, sizeof(_romfs_root_dev__gitkeep)/sizeof(_romfs_root_dev__gitkeep[0])}
};

static const rt_uint8_t _romfs_root_mnt_sata__gitkeep[] = {
0x20
};

static const struct romfs_dirent _romfs_root_mnt_sata[] = {
    {ROMFS_DIRENT_FILE, ".gitkeep", (rt_uint8_t *)_romfs_root_mnt_sata__gitkeep, sizeof(_romfs_root_mnt_sata__gitkeep)/sizeof(_romfs_root_mnt_sata__gitkeep[0])}
};

static const struct romfs_dirent _romfs_root_mnt[] = {
    {ROMFS_DIRENT_DIR, "sata", (rt_uint8_t *)_romfs_root_mnt_sata, sizeof(_romfs_root_mnt_sata)/sizeof(_romfs_root_mnt_sata[0])}
};

static const rt_uint8_t _romfs_root_tmp__gitkeep[] = {
0x20
};

static const struct romfs_dirent _romfs_root_tmp[] = {
    {ROMFS_DIRENT_FILE, ".gitkeep", (rt_uint8_t *)_romfs_root_tmp__gitkeep, sizeof(_romfs_root_tmp__gitkeep)/sizeof(_romfs_root_tmp__gitkeep[0])}
};

static const struct romfs_dirent _romfs_root[] = {
    {ROMFS_DIRENT_DIR, "dev", (rt_uint8_t *)_romfs_root_dev, sizeof(_romfs_root_dev)/sizeof(_romfs_root_dev[0])},
    {ROMFS_DIRENT_DIR, "mnt", (rt_uint8_t *)_romfs_root_mnt, sizeof(_romfs_root_mnt)/sizeof(_romfs_root_mnt[0])},
    {ROMFS_DIRENT_DIR, "tmp", (rt_uint8_t *)_romfs_root_tmp, sizeof(_romfs_root_tmp)/sizeof(_romfs_root_tmp[0])}
};

const struct romfs_dirent romfs_root = {
    ROMFS_DIRENT_DIR, "/", (rt_uint8_t *)_romfs_root, sizeof(_romfs_root)/sizeof(_romfs_root[0])
};
